workflows:
  ios-app:
    name: iOS App
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - xcodebuild build -workspace "smit.xcworkspace" -scheme "SMIT" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app